# Generated by Django 2.0.10 on 2019-05-21 11:11

from django.db import migrations, models
import django.db.models.deletion as deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('Course_Code', models.CharField(max_length=30)),
                ('Course_Name', models.CharField(max_length=200)),
                ('Professor', models.CharField(max_length=50)),
                ('Duration', models.IntegerField()),
                ('Attendees', models.IntegerField()),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LectureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('Lecture_No', models.IntegerField()),
                ('Title', models.CharField(max_length=100)),
                ('Live_Transcript', models.TextField()),
                ('Summary', models.TextField()),
                ('Tags', models.TextField(null=True)),
                ('Course', models.OneToOneField(to='ai_admin.CourseModels',
                                                on_delete=deletion.CASCADE,
                                                )),
            ],
        ),
    ]
