# Generated by Django 2.1.3 on 2019-06-20 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=50)),
                ('num_lectures', models.IntegerField(default=40)),
                ('num_enrolled', models.IntegerField(default=40)),
                ('image_cover', models.ImageField(upload_to='images/')),
                ('rating', models.DecimalField(decimal_places=1, default=8.0, max_digits=3,
                                               validators=[django.core.validators.MinValueValidator(0.0),
                                                           django.core.validators.MaxValueValidator(10.0)])),
            ],
        ),
        migrations.CreateModel(
            name='LectureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
    ]
