# Generated by Django 2.1.3 on 2019-06-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_admin', '0002_auto_20190620_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturemodel',
            old_name='Title',
            new_name='title',
        ),
    ]
