# Generated by Django 2.0.10 on 2019-05-05 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion as deletion
# Remaned django.db.models.deletion as deletion to statisfy pep


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=30)),
                ('discription', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('profile_image', models.ImageField(upload_to='')),
                ('user',
                 models.OneToOneField(on_delete=deletion.CASCADE,
                                      to=settings.AUTH_USER_MODEL)),
                # Remaned django.db.models.deletion as deletion to statisfy pep
            ],
        ),
    ]
