# Generated by Django 2.2.1 on 2019-05-19 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190519_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
