# Generated by Django 2.2.1 on 2019-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190621_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
