# Generated by Django 2.2.3 on 2019-07-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='created_by',
        ),
    ]
